version: '3.8'
services:
  app:
    build: .
    image: vinumsabbathi/crm:latest
    restart: unless-stopped
    env_file: .env
    depends_on:
    - db
    ports:
    - "8000:8000"
  db:
    image: postgres:15
    env_file: .env
    volumes:
    - pgdata:/var/lib/postgresql/data
volumes:
  pgdata: